### ISSUE TITLE
Auto Page Reload Issue on File Changes

### ISSUE THREAD

**Issue by nChauhan91** [Shakeskeyboarde/vite-live-preview#1]
Browser: Chrome 126
OS: MaxOS 14.5,
Package version: 0.1.8,
Package manager: npm 10.2.3 

The auto page reload feature is not working correctly. After successful build after file changes, the page does not refresh automatically, requiring manual reloads. In the console, we can see the output that the `page-reload` action was done.

<img width="388" alt="image" src="https://github.com/Shakeskeyboarde/vite-live-preview/assets/22027306/d018da2c-20f3-415b-958d-89b54c5fedf5">

**Comment by Shakeskeyboarde** [comment]
@nChauhan91 I've verified it using the same browser, os version, and package version.

- Are there any errors in the browser console or the network tab?
- Are you using the library as a plugin, or as a CLI?
- Can you post your vite config and project directory structure as well as the file you modified?
- Are you sure the page is not reloading?

**Comment by Shakeskeyboarde** [comment]
Also, if you would like to discuss in realtime, you can find me on the [Vite Land](https://discord.com/invite/vite) discord, this username (Shakeskeyboarde).

**Comment by Shakeskeyboarde** [comment]
Are you using https? If so, then I think it uses http/2, which doesn't support the web socket (http/1 upgrade request). I didn't test for that.

**Comment by nChauhan91** [comment]
> - Are there any errors in the browser console or the network tab?

No, there are no errors during build or in browser 

> - Are you using the library as a plugin, or as a CLI?

Tried both ways.

> - Can you post your vite config and project directory structure as well as the file you modified?

I'll try to create a new sample project soon & see if that helps, current setup is a big project that takes around 5 seconds to build. Not sure if that will have an impact.


> - Are you sure the page is not reloading?

Yes.

**Comment by Shakeskeyboarde** [comment]
The build time shouldn't have an effect, but I'll try reproducing it.

The refresh mechanism is pretty simple. You're seeing the console log for page-reload, so it's sending websocket messages to all connected clients immediately after that message. The reasons nothing might happen then are that the client is not connected, or the client script is not behaving as expected. If there are no client errors, that's puzzling. Are there client console messages and a websocket connection in the network tab?

In the browser console, you should see `[vite] connecting...` if the client script is loaded, and then a `[vite] connected` messages of the script successfully opens a websocket back to the server.

**Comment by Shakeskeyboarde** [comment]
I've released 0.1.12, which includes a fix for configuration handling, a fix for response compression, a fix for using the CLI if the Vite config also includes the plugin, and debug messaging. Try updating and adding the `--debug live-preview` option. And report back the output please.

**Comment by nChauhan91** [comment]
This version has fixed things, I can see logs in the terminal & the page also refreshes. 

Thanks 🙏🏻.

<img width="437" alt="image" src="https://github.com/Shakeskeyboarde/vite-live-preview/assets/22027306/c6cbe67d-0082-4e0b-810a-c6e288d91fbb">
