### ISSUE TITLE
Error on page reload after changes

### ISSUE THREAD

**Issue by rkorzhoff** [Shakeskeyboarde/vite-live-preview#3]
Hey! First I want to say that You are making awesome and very useful plugin!
But after last update I started to get such errors after page reload on changes.
It looks like it always looking for closing `>` after tag name
```
3:29:44 AM [vite] page-reload
[commonjs] Transform failed with 1 error:
/app/src/pages/new-recovery/index.vue?vue&type=script&setup=true&lang.ts:2:7: ERROR: Expected ">" but found "class"
file: /Users/robertkorzhov/work/tripster/frontend-experience-app/src/pages/new-recovery/index.vue?vue&type=script&setup=true&lang.ts:2:7

Expected ">" but found "class"
1  |  <template>
2  |    <div class="recovery">
   |         ^
3  |      <component :is="currentComponent" />
4  |    </div>
```
But It still seems work.
Can you check it? 
If need more details, let me know pls
Here are some deps versions:
```
"vite": "^5.4.0",
"vite-live-preview": "^0.3.2",
"vue": "^3.4.37",
```

**Comment by Shakeskeyboarde** [comment]
Thanks 😊!

I would be happy to take a look. I will need a minimal reproduction if possible, or if the code you're working on is public, that would work too.

**Comment by Shakeskeyboarde** [comment]
Closing for now due to no response. Also, I don't think this is related to the plugin. Please comment if it's still an issue and you can provide a repro, and I'll reopen.
